// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwh-sZiGjjGzM9ukJmLUy9bavHaApgDCI',
    appId: '1:171373392494:web:0511a5a5498bbcfddf2c7f',
    messagingSenderId: '171373392494',
    projectId: 'feira-digital-mxmlucca',
    authDomain: 'feira-digital-mxmlucca.firebaseapp.com',
    databaseURL: 'https://feira-digital-mxmlucca-default-rtdb.firebaseio.com',
    storageBucket: 'feira-digital-mxmlucca.firebasestorage.app',
    measurementId: 'G-NRY68VBHV0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRBisKGStgM0-tmS87n1H-hUST521hvnE',
    appId: '1:171373392494:android:3a54c91b38973763df2c7f',
    messagingSenderId: '171373392494',
    projectId: 'feira-digital-mxmlucca',
    databaseURL: 'https://feira-digital-mxmlucca-default-rtdb.firebaseio.com',
    storageBucket: 'feira-digital-mxmlucca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBFryIXRQzL3qYfAz6QolKmjTa5TaYv9Q',
    appId: '1:171373392494:ios:5fe7e196a47cb68ddf2c7f',
    messagingSenderId: '171373392494',
    projectId: 'feira-digital-mxmlucca',
    databaseURL: 'https://feira-digital-mxmlucca-default-rtdb.firebaseio.com',
    storageBucket: 'feira-digital-mxmlucca.firebasestorage.app',
    androidClientId: '171373392494-rchpakdqv94fr8p8s9i7s0d4ga0ituo0.apps.googleusercontent.com',
    iosClientId: '171373392494-9htb5ms1sk1aa6fgi8tc3pnvf4p6ltgf.apps.googleusercontent.com',
    iosBundleId: 'com.example.appFeiraDigital',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBFryIXRQzL3qYfAz6QolKmjTa5TaYv9Q',
    appId: '1:171373392494:ios:5fe7e196a47cb68ddf2c7f',
    messagingSenderId: '171373392494',
    projectId: 'feira-digital-mxmlucca',
    databaseURL: 'https://feira-digital-mxmlucca-default-rtdb.firebaseio.com',
    storageBucket: 'feira-digital-mxmlucca.firebasestorage.app',
    androidClientId: '171373392494-rchpakdqv94fr8p8s9i7s0d4ga0ituo0.apps.googleusercontent.com',
    iosClientId: '171373392494-9htb5ms1sk1aa6fgi8tc3pnvf4p6ltgf.apps.googleusercontent.com',
    iosBundleId: 'com.example.appFeiraDigital',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwh-sZiGjjGzM9ukJmLUy9bavHaApgDCI',
    appId: '1:171373392494:web:856b9638bbb29e42df2c7f',
    messagingSenderId: '171373392494',
    projectId: 'feira-digital-mxmlucca',
    authDomain: 'feira-digital-mxmlucca.firebaseapp.com',
    databaseURL: 'https://feira-digital-mxmlucca-default-rtdb.firebaseio.com',
    storageBucket: 'feira-digital-mxmlucca.firebasestorage.app',
    measurementId: 'G-90MWDCXFKE',
  );

}