import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart'; // Import Firebase Core

// Import the configuration files we created
import 'core/di/service_locator.dart';
import 'core/router/app_router.dart';
import 'core/theme/app_theme.dart';
// Import your firebase_options.dart generated by FlutterFire
import 'firebase_options.dart';

void main() async {
  // Ensures that Flutter bindings are initialized
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase (uncomment after running FlutterFire)
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // Initialize our Service Locator
  await setupLocator();

  // Run the application
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    // We use MaterialApp.router to integrate with go_router
    return MaterialApp.router(
      title: 'Feira Digital App',
      debugShowCheckedModeBanner: false,
      // Theme
      themeMode: ThemeMode.system,
      theme: AppTheme.lightTheme,
      darkTheme: AppTheme.darkTheme,
      routerConfig: router,
    );
  }
}
